/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DebugCatalogRouteImport } from './routes/debug.catalog'
import { Route as ApiCatalogVChar123versionChar125DotjsonRouteImport } from './routes/api/catalog.v{$version}[.]json'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugCatalogRoute = DebugCatalogRouteImport.update({
  id: '/debug/catalog',
  path: '/debug/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCatalogVChar123versionChar125DotjsonRoute =
  ApiCatalogVChar123versionChar125DotjsonRouteImport.update({
    id: '/api/catalog/v{$version}.json',
    path: '/api/catalog/v{$version}.json',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/debug/catalog': typeof DebugCatalogRoute
  '/api/catalog/v{$version}.json': typeof ApiCatalogVChar123versionChar125DotjsonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/debug/catalog': typeof DebugCatalogRoute
  '/api/catalog/v{$version}.json': typeof ApiCatalogVChar123versionChar125DotjsonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/debug/catalog': typeof DebugCatalogRoute
  '/api/catalog/v{$version}.json': typeof ApiCatalogVChar123versionChar125DotjsonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/debug/catalog' | '/api/catalog/v{$version}.json'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/debug/catalog' | '/api/catalog/v{$version}.json'
  id: '__root__' | '/' | '/debug/catalog' | '/api/catalog/v{$version}.json'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DebugCatalogRoute: typeof DebugCatalogRoute
  ApiCatalogVChar123versionChar125DotjsonRoute: typeof ApiCatalogVChar123versionChar125DotjsonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/catalog': {
      id: '/debug/catalog'
      path: '/debug/catalog'
      fullPath: '/debug/catalog'
      preLoaderRoute: typeof DebugCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/catalog/v{$version}.json': {
      id: '/api/catalog/v{$version}.json'
      path: '/api/catalog/v{$version}.json'
      fullPath: '/api/catalog/v{$version}.json'
      preLoaderRoute: typeof ApiCatalogVChar123versionChar125DotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DebugCatalogRoute: DebugCatalogRoute,
  ApiCatalogVChar123versionChar125DotjsonRoute:
    ApiCatalogVChar123versionChar125DotjsonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
